version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: projectnumer
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    restart: always
    ports:
      - "5500:5500"
    # environment:
    #   DATABASE_URL: mysql://myappuser:myapppassword@db:3306/myapp
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_DATABASE: projectnumer
      DB_PORT: 3306
    # links:
    #   - db
  frontend:
    build: ./numerproject
    ports:
     - "3000:3000"
    depends_on:
      - backend
